### ISSUE TITLE
Fehler in Detailansicht

### ISSUE THREAD

**Issue by ghost** [jweiland-net/pfprojects#4]
Ruft man aus der Liste ab dem zweiten Eintrag...
https://www.pforzheim.de/index.php?id=10878
...eine Detailansicht auf, dann kommt es zu einer Fehlermeldung:

_JWeiland\ServiceBw2\Domain\Repository\OrganisationseinheitenRepository::getById() must be of the type array, null returned_

**Comment by pascal20997** [comment]
Hey Erik,

habe ich mir soeben angeschaut. Wenn kein Veranstalter hinterlegt wurde, dann hat es wegen den Strict Types der service_bw2 geknallt. Habe das ganze entsprechend geupdated: https://github.com/jweiland-net/service_bw2/pull/45
